import random
roast = (
    "You're as useless as the 'ueue' in 'queue'.",
    "If I had a face like yours, I'd sue my parents.",
    "Some day you'll go far... and I hope you stay there.",
    "You must have been born on a highway cos' that's where most accidents happen.",
    "If i had a dollar for every time you said something smart, I'd be broke.",
    "When you were born the doctor threw you out the window and the window threw you back.",
    "If your brain was dynamite, there wouldn’t be enough to blow your hat off.",
    "Your face makes onions cry.",
    "I thought of you today, it reminded me to take out the trash.",
    "When karma comes back to punch you in the face, I want to be there in case it needs help.",
    "I thought I had the flu, but then I realized your face makes me sick to my stomach.",
    "You're like Mondays, everyone hates you.",
    "Keep rolling your eyes, you might find a barain back there.",
    "My phone battery lasts longer than your relationships",
    "I never forget a face, but in your case I would love to make an exception...",
    "You're so ugly when you look in the mirror your reflection looks away.",
    "You're so ugly when you were born, the doctor said aww what a treasure and your mom said yeah lets bury it.",
    "Maybe you should eat make-up so you’ll be pretty on the inside too.",
    "When you were born, the doctor came out to the waiting room and said to your dad, I'm very sorry. We did everything we could. But he pulled through.",
    "It’s a shame you can’t Photoshop your personality.",
    "Whoever told you to be yourself gave you really bad advice.",
    "If you could use 100 percent of your brain's power, you'd still be incredibly stupid. 100 percent of nothing is still nothing.",
    "Go ahead, tell us everything you know. It'll only take ten seconds.",
    "It’s not Halloweeen - take your mask off.",
    "You have a face like a smoke alarm. Beat at it until it sounds off.",
    "I never saw anybody take so long to type, and with such little result.",
    "My hair straightener is hotter than you.",
    "I’d explain it to you but I left my English-to-Dumbass Dictionary at home.",
    "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
    "I'd love to insult you, but I'm afraid I cannot perform as well as nature did.",
    "Everyone brings happiness to a room. I do when I enter, you do when you leave.",
    "The zoo called. They're wondering how you got out of your cage.",
    "I suggest you do a little soul searching. You might just find one.",
    "I’m visualizing duck tape over your mouth.",
    "You should use a glue stick instead of chapstick.",
    "I love what you have done to your hair. How'd you get it to come so far of your nostrils?",
    "I would roast you, but my mom said not to burn trash.",
    "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
    "If your family were Starwars figures, you'd be the special edition.",
    "Over watching paint dry and listening to you, I choose watching paint dry.",
    "If you uploaded a video to Youtube with your face, it would get demonetized for `Harmful or dangerous content`.",
    "Life is great, you should get one.",
    "Fake hair, fake nails, fake smile. Are you sure you weren't made in China?",
    "Your face looks like something I would draw with my non dominant hand.",
    "You're kind of like Rapunzel except instead of letting down your hair, you let down everyone in your life.",
    "I'd agree with you but then we'd both be wrong.",
    "Brains aren't everything, in fact in your case they're nothing.",
    "Why is it acceptable for you to be an idiot but not for me to point it out?",
    "Aww, it’s so cute when you try to talk about things you don’t understand.",
    "At least when I do a handstand my stomach doesn't hit me in the face.",
    "My hair straightener is hotter than you.",
    "If you’re going to be a smart ass, first you have to be smart, otherwise you’re just an ass.",
    "People like you are the reason why people like us need meds and therapy.",
    "Some people drink from the fountain of knowledge - it appears that you merely gargled.",
    "When I see your face theres not a thing I would change... Except for the direction im walking in.",
    "You sound reasonable... Time to up my medication.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "Did your parents ever ask you to run away from home?",
    "Hey, I found your nose, it’s in my business again!",
    "Is your butt jealous of the amount of crap that just came out of your mouth?",
    "Thinking isn't your strong suit, is it?",
    "Roses are red, violets are blue, god made us beautiful, but what happened to you?",
    "Are you in great physical pain, or is that your thinking expression?",
    "Your body fat is about as evenly distributed as wealth in the US economy.",
    "Where’s your off button?",
    "It may be that your whole purpose in life is simply to serve as a warning to others.",
    "You're the reason the gene pool needs a lifeguard.",
    "You are as useless as the 'ea' in 'Tea'.",
    "People miss you as much as fish misses dry land.",
    "I guess you prove that even god makes mistakes sometimes.",
    "Mirrors don't talk, and lucky for you, they don't laugh.",
    "I'd say you're funny, but looks aren't everything.",
    "I bet you wear a nose ring because no one wants to put one on your finger.",
    "I am not ignoring you. I am simply giving you time to reflect on what an idiot you are being.",
    "Are you always so stupid or is today a special occasion?",
    "I didn’t change. I grew up. You should try it sometime.",
    "You're so stupid I don't have the time or the crayons to explain this to you.",
    "If looks could kill, you’d soon find out that yours couldn’t.",
    "I heard you were born on a farm. Any more in the litter?",
    "Shrek just called, he said he will press charges on you for `Identity Theft`",
    "There are 1,013,150 words in the entire English dialect and yet there is not a single combination of them that describes my urge to hit you with a chair.",
    "Save your breath - you're going to need it to blow up your date.",
    "I’m busy right now, can I ignore you another time?",
    "Everyone is entitled to be a fool some of the time, but you abuse the privilege.",
    "You’re not pretty enough to have such an ugly personality.",
    "Your doctor called with your colonoscopy results. Good news – they found your head.",
    "I’m sorry, what language are you speaking? It sounds like bs.",
    "I’m not an astronomer but I am pretty sure the earth revolves around the sun and not you.",
    "You know that no matter how much you try, you're destined to lose.",
    "You may look like an idiot and talk like an idiot, but I don’t let that fool me. You really are an idiot.",
    "I heard you received a brain transplant but it rejected your body.",
    "You're so dumb that you got hit by a parked car.",
    "Don’t be ashamed of who you are. That’s your parents’ job.",
    "I am sorry. I cannot respond to you in any way. I am just not sufficiently interested in anything you have to say.",
    "Were you born this stupid or did you take lessons?",
    "Such a little mind - it must be lonely in such a big head.",
    "You're so ugly you make blind kids cry.",
    "You're so fat the only letters of the alphabet you know are KFC.",
    "I’m an acquired taste. If you don’t like me, acquire some taste.",
    "Too bad you can’t count jumping to conclusions and running your mouth as exercise.",
    "You look like what happens when you press random on the character creation menu.",
    "You’re pretty as a picture. I guess that explains why everyone wants to hang you.",
    "There hasn’t been a mistake this bad since Olaf the hairy, King of all the Vikings, ordered 80,000 battle helmets with the horns on the inside.",
    "I'm jealous of people that don't know you!",
    "You are more disappointing than an unsalted pretzel.",
    "You know nothing and think you know everything. That points clearly to a political career.",
    "I hear when you were a child your mother wanted to hire somebody to take care of you, but everyone said they would rather jump off a hill.",
    "Sorry, I can't understand. Idiotese is not my mother tongue.",
    "The last time I saw a face like yours I fed it a banana.",
    "You shouldn't play hide and seek, no one would look for you.",
    "Calm down. Take a deep breath and then hold it for about twenty minutes.",
    "Roses are red, violets are blue. I have five fingers and the middle one is for you.",
    "I might be crazy, but crazy is better than stupid.",
    "Have you been shopping lately? They’re selling lives – you should go get yourself one.",
    "I’ll never forget the first time we met. But I’ll keep trying.",
    "Being a stupid idiot is a tough job but someone has to do it.",
    "You’re the reason this country has to put directions on shampoo.",
    "Calling you an idiot would be an insult to all stupid people.",
    "You look like a monkey who’s been put in a suit and strategically shaved.",
    "Some babies were dropped on their heads but you were clearly thrown at a wall.",
    "You're so ugly, when you got robbed, the robbers made you wear their masks.",
    "No, no. I am listening. It just takes me a moment to process so much stupid information all at once.",
    "I would burn you but burning trash is bad for the environment.",
    "You have so many gaps in your teeth it looks like your tongue is in jail.",
    "If you’re offended by my opinion, you should hear the ones I keep to myself.",
    "You're so stupid, it takes you an hour to cook minute rice.",
    "I’d smack you, but that would be animal abuse.",
    "If I throw a stick, will you leave?",
    "Light travels faster than sound, which is why you seemed bright until you spoke.",
    "You are so annoying, you even make a Happy Meal cry.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "Hold still. I’m trying to imagine you with a personality.",
    "Your teeth are so bad you could eat an apple through a fence.",
    "I’m not insulting you; I’m describing you.",
    "You are the human version of period cramps.",
    "You are like a cloud. When you disappear, it’s a beautiful day.",
    "I’d rather treat a baby’s diaper rash than have lunch with you.",
    "You just might be why the middle finger was invented in the first place.",
    "The last time I saw something like you… I flushed.",
    "I was going to make a joke about your life, but I see life beat me to the punch.",
    "Life is full of disappointments, and I just added you to the list.",
    "I treasure the time I don’t spend with you.",
    "Since you know it all, you should know when to shut up.",
    "If I wanted to hear from an asshole, I’d fart.",
    "I’d give you a nasty look, but you’ve already got one.",
    "Of course I’m talking like an idiot… how else could you understand me?",
    "You have an entire life to be an idiot. Why not take today off?",
    "I might be crazy, but crazy is better than stupid.",
    "It’s scary to think people like you are allowed to vote.",
    "I missed you as much as fish misses dry land",
    "You sound better with your mouth closed",
    "Do you still love nature....despite what it did to you?",
    "Do you have to leave so soon? I was just about to poison the tea.",
    "You're so ugly Hello Kitty said goodbye to you.",
    "You are so ugly that when your mama dropped you off at school she got a fine for littering.",
    "I would ask how old you are, but I know you can't count that high.",
    "If you were twice as smart, you'd still be stupid.",
    "I could eat a bowl of alphabet soup and crap out a smarter comeback than what you just said.",
)


def getroast():
    return random.choice(roast)
